### PR TITLE
plugin: fixes to keep Cordova 8 and 7 support

### PR DESCRIPTION
**Pull request by jaimecbernardo**
Adds xcode dependency to use with require.
Reverts cordova-lib to requireCordovaModule, since it's a cordova
module.

### CODE REVIEW

**Review by hanieel — CHANGES_REQUESTED** [review]
This change you are asking for does not make it to support cordova 9. it crashes in cordova 9 due to deprecation of requireModule.  what is the purpose of including xcode dependency?? 
 what does that do?? 
This PR I have should be backward compatible.  pls remove your change.

**Comment by jaimecbernardo** [comment]
Hi @hanieel ,

I've tried the PR with projects created with older Cordova versions and it didn't work because the hooks couldn't find the modules.

The `xcode` dependency needed by the iOS hooks may not be found by `require` unless it's a direct dependency of the module or Cordova installs it in the topmost `node_modules` path. On older versions `xcode` is installed as a dependency of `cordova-ios` which means it may fail through `require`.

According to [the cordova-lib 9.0.0 release notes](https://cordova.apache.org/announcements/2019/03/18/cordova-lib-release-9.0.0.html), `requireCordovaModule` was deprecated for "non-Cordova modules". `cordova-lib` is a cordova module and is required through `requireCordovaModule` for the Android plugins.

> it crashes in cordova 9 due to deprecation of requireModule.

What crash are you getting with the changes in this PR?

**Comment by hanieel** [comment]
@jamiecbernardo I have tested my PR on these versions:
**Cordova 7.0** - Works as expected
**Cordova 8.0** - _(does require xcode dep.)_ need to specify a **cordova-android 7.1.1** cordova-android 
                         that comes with **cordova 8** which is **cordova-android 7.0.0** has issues. 
**Cordova 8.1** - _(does require xcode dep.)_ Works as expected.
**Cordova 9.0** - Works as expected. 


The error I get in cordova 9 is: _Error: requireCordovaModule was deprecated for non-Cordova modules use require instead._ everytime I try to build with cordova 9. 

Have you ran it using Cordova 9 yet?

**Comment by jaimecbernardo** [comment]
I'm getting a `Error: Cannot find module 'cordova-lib'` when trying to prepare an Android project on Cordova 9 with the main branch from this repo. Here are the commands I'm following:

```
npm install -g cordova@9
git clone https://github.com/hanieel/nodejs-mobile-cordova
cordova create TestPR
cd TestPR
cordova platform add android
cordova plugin add ../nodejs-mobile-cordova
cordova prepare android
```

What commands are you running with the changes I've proposed to get the error you mention?

In my case, it works. Here are the commands I'm using to test this PR:
```
npm install -g cordova@9
git clone https://github.com/hanieel/nodejs-mobile-cordova
cordova create TestPR
cd nodejs-mobile-cordova
git fetch origin pull/1/HEAD:pr1
git checkout pr1
cd ../TestPR
cordova platform add android
cordova plugin add ../nodejs-mobile-cordova
cordova prepare android
```
Does this fail for you?

**Comment by jaimecbernardo** [comment]
Hi, Ended up merging these changes with the fixes needed for keeping support for older versions upstream: https://github.com/JaneaSystems/nodejs-mobile-cordova/commit/72ede371fcf110876f0ddfa176bc161dede0687d

**Pull request closed without merging**
